[inovacao-T426] tests: configuração e adição dos testes
agro1desenvolvimento/utils-js pull request #3
Opened 2021-01-12 19:37 UTC by GustavoChiochetta

2021-01-12 20:18 UTC, GregoryEsberci requested changes

2021-01-12 20:18 UTC, GregoryEsberci commented on __tests__/keys-to-camel-case-deep.test.ts
> +test('keys should be in camel case', () =>{
melhorar cobertura dos testes, pode ser enviado um array, um objeto/array vazio e outras variações, mas acho q esses 2 casos podem causar bugs, isso vale para os outros testes tbm

2021-01-12 20:18 UTC, GregoryEsberci commented on babel.config.js
> +module.exports = {
o babel é necessário?
o typescript está fazendo o build
https://github.com/agro1desenvolvimento/utils-js/blob/main/package.json#L12

2021-01-12 20:18 UTC, GregoryEsberci commented on package.json
> +  "jest": {
mover configuração para o `jest.config.ts`

2021-01-14 17:57 UTC, GustavoChiochetta commented on babel.config.js
> +module.exports = {
foi necessário, os testes falham caso eu n use o babel. a documentação também aconselha o uso. https://jestjs.io/docs/en/getting-started

2021-01-14 19:09 UTC, GregoryEsberci commented on babel.config.js
> +module.exports = {
então não é melhor deixar o babel responsável pelo build?
Da forma que está atualmente é testado um código é enviado para produção outro que é um pouco diferente

2021-01-15 14:08 UTC, GregoryEsberci approved these changes

2021-01-15 14:08 UTC, merged